swagger: 2.0
info:
  version: v1
  title: Portfolio Management Service API
  description: |
     Portfolio Management Service

  contact:
    name: COSMIC IT GmbH
    email: info@cosmicit.de
schemes:
  - http
  - https
tags:
  - name: Public API
    description: API which can be accessed publicly
  - name: User API
    description: API with Customer Token in Future
  - name: Admin API
    description: API with for admin user
  - name: customer
    description: Data access on `Customer (Future)`
produces:
  - application/json
consumers:
  - application/json
paths:
  /user:
    $ref: 'v1/customer.yml#/customer'
  /user/{id}:
    $ref: 'v1/customer.yml#/customerId'
  /agent:
    $ref: 'v1/agent.yml#/agent'
  /agent/{id}:
    $ref: 'v1/agent.yml#/agentId'
  /outlet:
    $ref: 'v1/outlet.yml#/outlet'
  /outlet/{id}:
    $ref: 'v1/outlet.yml#/outletId'
  /serviceprovider:
    $ref: 'v1/serviceProvider.yml#/serviceProvider'
  /serviceprovider/{id}:
    $ref: 'v1/serviceProvider.yml#/serviceProviderId'
  /document:
    $ref: 'v1/document.yml#/document'
  /document/{id}:
    $ref: 'v1/document.yml#/documentId'
  /document/upload/{documenttype}:
    $ref: 'v1/document.yml#/uploadEntity'
  /subscription:
    $ref: 'v1/subscription.yml#/subscription'
  /subscription/{id}:
    $ref: 'v1/subscription.yml#/subscriptionId'
  /promotion:
    $ref: 'v1/promotion.yml#/promotion'
  /promotion/{id}:
    $ref: 'v1/promotion.yml#/promotionId'
  /servicecontract:
    $ref: 'v1/serviceContract.yml#/serviceContract'
  /servicecontract/{id}:
    $ref: 'v1/serviceContract.yml#/serviceContractId'
  /servicerequest:
    $ref: 'v1/serviceRequest.yml#/serviceRequest'
  /servicerequest/{id}:
    $ref: 'v1/serviceRequest.yml#/serviceRequestId'





