swagger: 2.0
info:
  version: v1
  title: Portfolio Management Service API
  description: |
     Portfolio Management Service

  contact:
    name: COSMIC IT GmbH
    email: info@cosmicit.de
schemes:
  - http
  - https
tags:
  - name: Public API
    description: API with Client Token
  - name: User API
    description: API with User Token
  - name: Admin API
    description: API with Admin Token
  - name: user
    description: Data access on `User`
produces:
  - application/json
consumers:
  - application/json
paths:
  /user:
    $ref: 'v1/user.yml#/user'
  /user/{id}:
    $ref: 'v1/user.yml#/userId'



